using RECVXFlagTool.Models.Base;

namespace RECVXFlagTool.Models
{
    public class RoomModel : BaseNotifyModel
    {
        private int _id;
        public int Id
        {
            get => _id;
            set
            {
                if (SetField(ref _id, value))
                    Name = GetName();
            }
        }

        private string _name;
        public string Name
        {
            get
            {
                if (string.IsNullOrEmpty(_name))
                    _ = SetField(ref _name, GetName());
                return _name;
            }
            set => SetField(ref _name, value);
        }

        private string GetName() => Id switch
        {
            0x0000 => "Prison B1 Cells",
            0x0001 => "Prison B1 Entry",
            0x0002 => "Prison 1F Graveyard",
            0x0003 => "Prison 1F Yard",
            0x0004 => "Prison 1F Computer Room",
            0x0005 => "Prison 1F Barracks Yard",
            0x0006 => "Prison 1F Barracks",
            0x0007 => "Prison 1F Bunkhouse",
            0x0008 => "Prison 1F Execution Yard",
            0x0009 => "Prison 1F Security Corridor",
            0x000A => "Prison Iron Bridge",
            0x000B => "Prison 1F Clinic",
            0x000C => "Prison 1F Cremetorium",
            0x000D => "Prison 1F Secret Corridor",
            0x000E => "Prison 1F Torture Chamber",
            0x000F => "Prison 1F Statue Room",
            0x0010 => "Prison 1F Backyard",
            0x0100 => "Palace Courtyard",
            0x0102 => "Palace Entrance Hall",
            0x0103 => "Palace 1F Bathroom",
            0x0104 => "Palace 1F Portrait Room",
            0x0105 => "Palace 1F Display Room",
            0x0106 => "Palace 1F Umbrella Meeting Room",
            0x0107 => "Palace 1F Corridor",
            0x0108 => "Palace 2F Secretarys Office",
            0x0109 => "Palace 2F Alfreds Office",
            0x010A => "Palace 2F Residence Bridge",
            0x010B => "Palace 2F Casino Lounge",
            0x010C => "Palace Passage",
            0x010D => "Palace B1 Dock",
            0x010E => "Palace B1 Submarine",
            0x0200 => "Private Residence Courtyard",
            0x0201 => "Private Residence Entrance Hall",
            0x0202 => "Private Residence 1F Dining Room",
            0x0203 => "Private Residence 2F Bedroom Corridor",
            0x0204 => "Private Residence 2F Alfreds Bedroom",
            0x0205 => "Private Residence 2F Alexias Bedroom",
            0x0206 => "Private Residence 3F Play Room",
            0x0207 => "Private Residence 4F Private Study",
            0x0300 => "Military Training Facility Garage",
            0x0301 => "Military Training Facility Back Courtyard",
            0x0302 => "Military Training Facility 1F Tank Yard",
            0x0303 => "Military Training Facility 1F Elevator Corridor",
            0x0304 => "Military Training Facility 1F Diorama Room",
            0x0305 => "Military Training Facility 1F Lockers",
            0x0306 => "Military Training Facility 1F Swimming Pool",
            0x0307 => "Military Training Facility 1F Front Office",
            0x0308 => "Military Training Facility Lobby",
            0x0309 => "Military Training Facility 1F Excercise Yard",
            0x030A => "Military Training Facility Warehouse",
            0x030B => "Military Training Facility 2F Warehouse Managers Room",
            0x030C => "Military Training Facility 2F Command Center",
            0x030D => "Military Training Facility 2F Emergency Door",
            0x030F => "Military Training Facility 2F Warehouse Corridor",
            0x0310 => "Military Training Facility B1 Basement Storehouse",
            0x0311 => "Military Training Facility B1 Boiler Room",
            0x0312 => "Military Training Facility B1 Turn Table Room",
            0x0313 => "Military Training Facility B1 Chemical Storage Room",
            0x0314 => "Military Training Facility B1 Weapon Repair Shop",
            0x0315 => "Military Training Facility B1 Iron Walkway",
            0x0316 => "Military Training Facility Elevator",
            0x0317 => "Military Training Facility Cargo Elevator",
            0x0318 => "Military Training Facility Jet Hangar Corridor",
            0x0400 => "Airport Check-in",
            0x0401 => "Airport Bridge",
            0x0402 => "Airport Cargo Bay",
            0x0403 => "Airport Entry",
            0x0404 => "Airport Cargo Transport",
            0x0405 => "Airport Submarine",
            0x0500 => "Transport Plane Cockpit",
            0x0501 => "Transport Plane Cargo Hold",
            0x0600 => "Antartic Transport Terminal B1 Silo",
            0x0601 => "Antartic Transport Terminal B1 Workmans Bunkhouse",
            0x0602 => "Antartic Transport Terminal B1 Tool Storeroom",
            0x0603 => "Antartic Transport Terminal B2 Frozen Corridor",
            0x0604 => "Antartic Transport Terminal B2 Office",
            0x0605 => "Antartic Transport Terminal Sorting Room",
            0x0606 => "Antartic Transport Terminal Mining Room",
            0x0607 => "Antartic Transport Terminal Power Room",
            0x0608 => "Antartic Transport Terminal B2 Weapon Room",
            0x0609 => "Antartic Transport Terminal B2 B.O.W. Room",
            0x060A => "Antartic Transport Terminal 1F Helipad",
            0x0700 => "Military Training Facility 1F Tank Yard",
            0x0701 => "Military Training Facility Elevator",
            0x0702 => "Military Training Facility 1F Diorama Room",
            0x0703 => "Military Training Facility 2F Command Center",
            0x0704 => "Military Training Facility B1 Weapon Repair Shop",
            0x0705 => "Military Training Facility B1 Chemical Storage Room",
            0x0706 => "Military Training Facility Iron Walkway",
            0x0707 => "Military Training Facility Specimen Lab",
            0x0708 => "Military Training Facility B2 Jet Hangar Corridor",
            0x0709 => "Military Training Facility B2 Captins Room",
            0x070A => "Military Training Facility B2 Water Pool",
            0x070B => "Military Training Facility B1 Turn Table Room",
            0x070C => "Military Training Facility Garage",
            0x070D => "Military Training Facility 1F Excercise Yard",
            0x070E => "Military Training Facility Back Courtyard",
            0x070F => "Military Training Facility 1F Front Office",
            0x0710 => "Military Training Facility 1F Lobby",
            0x0711 => "Military Training Facility 2F Lobby",
            0x0712 => "Military Training Facility 2F Warehouse Corridor",
            0x0713 => "Military Training Facility 1F Elevator Corridor",
            0x0714 => "Military Training Facility B1 Basement Storehouse",
            0x0715 => "Military Training Facility B1 Boiler Room",
            0x0716 => "Military Training Facility B3 Cave",
            0x0717 => "Military Training Facility B3 Tomb",
            0x0718 => "Military Training Facility B3 Cave Cinematic",
            0x0719 => "Military Training Facility B1 Underground Passage",
            0x0800 => "Airport Check-in",
            0x0801 => "Airport Bridge",
            0x0802 => "Airport Cargo Bay",
            0x0803 => "Airport Bridge Cinematic",
            0x0804 => "Airport Cargo Transport",
            0x0805 => "Airport Entry",
            0x0900 => "Antartic Transport Terminal B1 Silo",
            0x0901 => "Antartic Transport Terminal B1 Workmans Bunkhouse",
            0x0902 => "Antartic Transport Terminal B1 Tool Storeroom",
            0x0903 => "Antartic Transport Terminal B2 Frozen Corridor",
            0x0904 => "Antartic Transport Terminal B2 Office",
            0x0905 => "Antartic Transport Terminal B1 Sorting Room",
            0x0906 => "Antartic Transport Terminal B1 Mining Room",
            0x0907 => "Antartic Transport Terminal B1 Power Room",
            0x0908 => "Antartic Transport Terminal B2 Weapon Room",
            0x0909 => "Antartic Transport Terminal B1 Jet Hanger",
            0x090A => "Antartic Transport Terminal B1 Corridor",
            0x090B => "Antartic Transport Terminal B1 Water Tank Room",
            0x090C => "Antartic Transport Terminal B5 Icy Corridor",
            0x090D => "Antartic Transport Terminal B5 Mansion Courtyard",
            0x090E => "Antartic Transport Terminal B5 High Voltage Room",
            0x090F => "Antartic Transport Terminal B5 Main Hall",
            0x0910 => "Antartic Transport Terminal B5 Art Room",
            0x0911 => "Antartic Transport Terminal B6 Ant Farm",
            0x0912 => "Antartic Transport Terminal B6 Alexias Lab",
            0x0913 => "Antartic Transport Terminal B6 Alexias Study",
            0x0914 => "Antartic Transport Terminal B4 Bedroom Corridor",
            0x0915 => "Antartic Transport Terminal B4 Study",
            0x0916 => "Antartic Transport Terminal B4 T-Veronica Lab",
            0x0917 => "Antartic Transport Terminal B4 Alfreds Bedroom",
            0x0918 => "Antartic Transport Terminal B4 Alexias Bedroom",
            0x0919 => "Antartic Transport Terminal B3 Conference Room",
            0x091A => "Antartic Transport Terminal B4 Sitting Room",
            0x091B => "Antartic Transport Terminal B4 L Corridor",
            0x091C => "Antartic Transport Terminal B4 Hall of Armors",
            0x091D => "Antartic Transport Terminal B4 Detention Center",
            0x091E => "Antartic Transport Terminal B4 Upper Ant Farm",
            0x091F => "Antartic Transport Terminal B4 Reactor Core",
            0x0920 => "Antartic Transport Terminal B5 Main Hall Destroyed",
            0x0922 => "Antartic Transport Terminal End Cinematic 1",
            0x0923 => "Antartic Transport Terminal End Cinematic 2",
            0x0924 => "Antartic Transport Terminal End Cinematic 3",
            0x0925 => "Antartic Transport Terminal End Cinematic 4",
            0x0534 => "Battle Time Room 1",
            0x0535 => "Battle Time Room 2",
            0x0536 => "Battle Time Room 3",
            0x0537 => "Battle Time Room 4",
            0x053A => "Battle Time Room 5",
            0x053B => "Battle Time Room 6",
            0x053C => "Battle Time Room 7",
            0x053F => "Battle Time Room 8",
            0x0540 => "Battle Time Room 9",
            0x0541 => "Battle Time Room 10",
            0x0542 => "Battle Time Room 11",
            0x0543 => "Battle Time Room 12",
            0x0544 => "Battle Time Room 13",
            0x0545 => "Battle Time Room 14",
            0x0546 => "Battle Time Room 15",
            0x0547 => "Battle Time Room 16",
            0x0550 => "Battle Time Boss 17",
            _ => "No Room Loaded",
        };
    }
}