name: Build RDXplorer release

on:
  push:
    tags:
      - rdxplorer-release

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    permissions:
      contents: write
      id-token: write

    env:
      Project_Name: RDXplorer
      Release_Name: RDXplorer
      Release_Body: RDXplorer
      Asset_Name: rdxplorer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO: Confirm that the project version has been increased before proceeding
      - name: Get release info
        id: info
        shell: pwsh
        run: |
          [xml]$proj = Get-Content "${{ env.Project_Name }}/${{ env.Project_Name }}.csproj"
          $projVersion = $proj.Project.PropertyGroup.AssemblyVersion
          $version = "$projVersion".Trim()
          echo "release=$version" >> $env:GITHUB_OUTPUT

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ${{ env.Project_Name }}

      - name: Build release
        run: dotnet build ${{ env.Project_Name }} -c Release --no-restore

      - name: Publish release
        run: dotnet publish ${{ env.Project_Name }} -c Release -o .\publish --no-restore --no-build

      - name: Create zip
        run: Compress-Archive -Path .\publish\* -Destination release.zip

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./release.zip
          asset_name: ${{ env.Asset_Name }}-${{ steps.info.outputs.release }}.zip
          release_name: ${{ env.Release_Name }} (${{ steps.info.outputs.release }})
          body: ${{ env.Release_Body }} ${{ steps.info.outputs.release }}
          tag: ${{ env.Asset_Name }}-${{ steps.info.outputs.release }}
          overwrite: true
